package demo.model;

public class ContentWithBLOBs extends Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.icon
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.text
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.icon
     *
     * @return the value of content.icon
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    @Override
    public String getIcon() {
        return icon;
    }

    @Override
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.text
     *
     * @return the value of content.text
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    @Override
    public String getText() {
        return text;
    }

    @Override
    public void setText(String text) {
        this.text = text;
    }
}