package demo.model;

import java.util.Date;

public class Trx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trx.id
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trx.contentId
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */
    private int contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trx.personId
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */
    private int personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trx.price
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trx.time
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */
    private long time;

    private String icon;

    private String title;

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getContentid() {
        return contentid;
    }

    public void setContentid(int contentid) {
        this.contentid = contentid;
    }

    public int getPersonid() {
        return personid;
    }

    public void setPersonid(int personid) {
        this.personid = personid;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trx.id
     *
     * @return the value of trx.id
     *
     * @mbggenerated Mon Nov 11 10:49:21 CST 2019
     */



    public Trx() {

    }

    public Trx(int id, int contentid, int personid, double price, long time, String icon, String title) {
        this.id = id;
        this.contentid = contentid;
        this.personid = personid;
        this.price = price;
        this.time = time;
        this.icon = icon;
        this.title = title;
    }

    @Override
    public String toString() {
        return "Trx{" +
                "id=" + id +
                ", contentid=" + contentid +
                ", personid=" + personid +
                ", price=" + price +
                ", time=" + time +
                ", icon='" + icon + '\'' +
                ", title='" + title + '\'' +
                '}';
    }
}