package demo.model;

import java.util.Arrays;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.price
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.title
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.remark
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String remark;

//    private byte[] icon;

    private String icon;

    private String text;

    private String isbuy;

    private String issell;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.price
     *
     * @return the value of content.price
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.title
     *
     * @return the value of content.title
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.title
     *
     * @param title the value for content.title
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.remark
     *
     * @return the value of content.remark
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.remark
     *
     * @param remark the value for content.remark
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getIsbuy() {
        return isbuy;
    }

    public void setIsbuy(String isbuy) {
        this.isbuy = isbuy;
    }

    public String getIssell() {
        return issell;
    }

    public void setIssell(String issell) {
        this.issell = issell;
    }

    public Content() {

    }

    public Content(int id, double price, String title, String remark, String icon, String text, String isbuy, String issell) {
        this.id = id;
        this.price = price;
        this.title = title;
        this.remark = remark;
        this.icon = icon;
        this.text = text;
        this.isbuy = isbuy;
        this.issell = issell;
    }

    @Override
    public String toString() {
        return "Content{" +
                "id=" + id +
                ", price=" + price +
                ", title='" + title + '\'' +
                ", remark='" + remark + '\'' +
                ", icon='" + icon + '\'' +
                ", text='" + text + '\'' +
                ", isbuy='" + isbuy + '\'' +
                ", issell='" + issell + '\'' +
                '}';
    }
}