package demo.model;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.userName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.password
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.nickName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.userType
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    private Byte usertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.userName
     *
     * @return the value of person.userName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.userName
     *
     * @param username the value for person.userName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.password
     *
     * @return the value of person.password
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.password
     *
     * @param password the value for person.password
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.nickName
     *
     * @return the value of person.nickName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.nickName
     *
     * @param nickname the value for person.nickName
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.userType
     *
     * @return the value of person.userType
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public Byte getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.userType
     *
     * @param usertype the value for person.userType
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    public void setUsertype(Byte usertype) {
        this.usertype = usertype;
    }

    public Person() {

    }

    public Person(Integer id, String username, String password, String nickname, Byte usertype) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.nickname = nickname;
        this.usertype = usertype;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", nickname='" + nickname + '\'' +
                ", usertype=" + usertype +
                '}';
    }
}