package demo.mapper;

import demo.mapper.base.BaseMapper;
import demo.model.Content;
import demo.model.ContentExample;
import demo.model.ContentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentMapper extends BaseMapper<Content> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    void insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int insertSelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    List<ContentWithBLOBs> selectByExampleWithBLOBs(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    ContentWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") ContentWithBLOBs record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ContentWithBLOBs record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByPrimaryKeySelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbggenerated Thu Nov 07 09:32:03 CST 2019
     */
    int updateByPrimaryKey(Content record);

    List<Content> findAllwBuy();  //查看为购买的内容

    List<Content> findAllyBuy();  //查看已购买的内容

}